---
services:
  mqtt-broker-v5:
    container_name: mqtt-broker-v5
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "8899:8080"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data